$schema: 'https://azuremlschemas.azureedge.net/latest/commandJob.schema.json'
environment:
  image: library/python:3.10
code: ./
command: |
  python3 -m pip install --no-cache-dir --upgrade pip
  python3 -m pip install -r requirements.txt
  python3 azure_test.py ${{outputs.outdir}}
compute: 'cpu-1-core'
resources:
  instance_count: 1
outputs:
  outdir:
    type: uri_folder
    path: azureml://subscriptions/e016b4a6-4e0e-43d2-b05e-4b5df8ce5fe6/resourcegroups/sigrun.may-rg/workspaces/wp2/datastores/workspaceblobstore/paths/UI/2024-01-14_165659_UTC/
    mode: rw_mount
experiment_name: colon_01
display_name: train_colon_03

# az ml job create --file azure_config.yaml --workspace-name wp2 --resource-group sigrun.may-rg
