experiment_id = "test4"
description = "testing" # "Colon cancer dataset with random RF, mannwhitneyu instead of welsh for colon_random"
verbose_optuna = true
n_trials_optuna = 100

pickle_preprocessed_data = true

[cv]
n_outer_folds = 15

[data]
train_correlation_threshold = 0.2
name = "data"
path = "../../data/data.csv"


#[rf_parameters]
#classifier = {}
#regressor = {}

