# Copyright (c) 2024 Sigrun May,
# Ostfalia Hochschule für angewandte Wissenschaften
#
# This software is distributed under the terms of the MIT license
# which is available at https://opensource.org/licenses/MIT


#experiment_id = "prostate_s00"
#description = "Prostate cancer dataset"

experiment_id = "colon_s10"
description = "Colon cancer dataset"

method = "reverse_random_forest"
# method = "standard_random_forest"


# standard parameters
verbose_optuna = true
n_trials_optuna = 50
# random_state = 42

# reverse selection parameters
random_seeds = [29, 10,  17, 42, 234, 34, 1, 5, 19, 3, 23, 9, 7, 123, 234, 345, 456, 567, 678, 789, 890, 15, 23, 34, 45, 56, 67, 78, 89, 90,]
# random_seeds = [42,234,34,23,5,3,9,7, 123, 234,]
# random_seeds = [42,34,23,5,3]
train_correlation_threshold = 0.2

[cv]
n_outer_folds = 0
loo = true
pickle_preprocessed_data = false

[data]
# name = "prostate"
name = "colon"

# path = "./data/artificial_biomarker_data_2.csv"
path = ""
scale = false
