name: Static Code Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # at 4 am
    - cron:  '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    env:
      src: "reverse_feature_selection"
      other-src: "tests docs"

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-python
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install --with lint,test,doc

    - name: Check with black
      run: poetry run black ${{ env.src }} ${{ env.other-src }} --check --diff

    - name: Check with mdformat
      run: poetry run mdformat --check --number .

    - name: Check Sphinx doctest
      run: poetry run make -C docs doctest